apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 72.3.1
      chart: kube-prometheus-stack
      helm:
        valueFiles:
          - $values/prometeus/values.yaml
    - repoURL: "https://github.com/Suselkowy/sandbox.git"
      ref: values
    - repoURL: "https://github.com/Suselkowy/sandbox.git"
      path: "prometeus"
      targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
