# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: nginx-deployment
#   namespace: argo-demo
#   labels:
#     app: nginx
# spec:
#   replicas: 3
#   selector:
#     matchLabels:
#       app: nginx
#   template:
#     metadata:
#       labels:
#         app: nginx
#     spec:
#       containers:
#         - name: nginx
#           image: nginx:1.21.6
#           ports:
#             - containerPort: 80
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx-service
#   namespace: argo-demo
# spec:
#   selector:
#     app: nginx
#   ports:
#     - port: 80
#       targetPort: 80
#   type: ClusterIP
# ---
# # For external access
# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx-service-lb
#   namespace: argo-demo
# spec:
#   selector:
#     app: nginx
#   ports:
#     - port: 8080
#       targetPort: 80
#   type: LoadBalancer
