apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd-metrics
  namespace: argocd
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-metrics
  endpoints:
    - port: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: example-hotrod
  namespace: example-hotrod
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: example-hotrod
  endpoints:
    - port: frontend
      path: /metrics
