prometheus-node-exporter:
  enabled: false
prometheus-prometheus-node-exporter:
  enabled: false
grafana:
  enabled: true
  defaultDashboardsEnabled: true
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
